# Generated by Django 5.1.1 on 2025-07-20 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0016_unknownloginattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("rename", "Rename"),
                            ("trim", "Trim"),
                            ("remove_audio", "Remove Audio"),
                            ("convert_360_video", "Convert 360 Video"),
                            ("pause_manual", "Pause for Manual Edit"),
                            ("zip_files", "Zip Files"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="bookings.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
