# Generated by Django 5.1.1 on 2025-07-20 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_workflow_workflowstep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="confirmation_number",
        ),
        migrations.RemoveField(
            model_name="message",
            name="read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="responded_by",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response",
        ),
        migrations.AddField(
            model_name="message",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="bookings.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
