# Generated by Django 5.1.1 on 2025-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0020_workflowrun_output_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_review_request",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
