# Generated by Django 5.1.1 on 2025-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0019_workflowrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="output_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
