# Generated by Django 5.1.1 on 2025-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0021_message_is_review_request_workflow_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("convert_360_video", "Convert Media"),
                    ("rename", "Rename Files"),
                    ("remove_audio", "Remove Audio"),
                    ("trim", "Crop Video"),
                    ("organize_files", "Place Files in Folders"),
                ],
                max_length=50,
            ),
        ),
    ]
