# Generated by Django 5.1.1 on 2025-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0022_workflowstep_config_alter_workflowstep_step_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="pause_between_steps",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("setup_structure", "Setup Folder Structure"),
                    ("convert_360_video", "Convert Media"),
                    ("rename", "Rename Files"),
                    ("remove_audio", "Remove Audio"),
                    ("trim", "Crop Video"),
                    ("organize_files", "Place Files in Folders"),
                ],
                max_length=50,
            ),
        ),
    ]
