# Generated by Django 5.1.1 on 2025-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0023_workflowrun_pause_between_steps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="qa_video_review",
            field=models.BooleanField(
                default=False, help_text="Require manual QA review for each video"
            ),
        ),
    ]
