# Generated by Django 5.1.1 on 2025-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0024_workflow_qa_video_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="crop_end_seconds",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="crop_start_seconds",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="remove_audio",
            field=models.BooleanField(default=False),
        ),
    ]
