# Generated by Django 5.2.4 on 2025-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0025_workflowstep_crop_end_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="use_date_suffix",
            field=models.BooleanField(
                default=False,
                help_text="Use processing date instead of numeric version",
            ),
        ),
    ]
