# Generated by Django 5.2.4 on 2025-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0026_workflow_use_date_suffix"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="initials",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
