# Generated by Django 5.1.1 on 2025-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0027_profile_initials"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="from_shared",
            field=models.BooleanField(
                default=False,
                help_text="Indicates this workflow originated from the shared library",
            ),
        ),
    ]
