# Generated by Django 5.1.1 on 2025-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0028_workflow_from_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="awaiting_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="rejection_comment",
            field=models.TextField(blank=True),
        ),
    ]
