# Generated by Django 5.1.1 on 2025-08-04 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0029_workflow_awaiting_review_workflow_rejection_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="source_creator",
            field=models.ForeignKey(
                blank=True,
                help_text="Original creator if this workflow was imported",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
