# Generated by Django 5.1.1 on 2025-08-04 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0030_workflow_source_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="downloaded_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have downloaded this workflow",
                related_name="downloaded_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
