# Generated by Django 5.1.1 on 2025-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0031_workflow_downloaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
