# Generated by Django 5.1.1 on 2025-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0033_message_responded_by_message_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="current_action",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="current_step",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
