# Generated by Django 5.1.1 on 2025-08-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0034_workflowrun_current_action_workflowrun_current_step_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflowstep",
            old_name="step_type",
            new_name="action",
        ),
    ]
